// 좀비 아포칼립스 생존 유형 — 언어팩 [en, es, id, ja, th, zh(간체), tw(번체)]
(function () {
  if (!window.GoblubI18n) return;
  GoblubI18n.add({
    "좀비 아포칼립스 생존 유형": ["Zombie Apocalypse Survival Type", "Tipo de supervivencia zombi", "Tipe Bertahan Kiamat Zombi", "ゾンビアポカリプス生存タイプ", "ประเภทเอาตัวรอดซอมบี้", "丧尸末日生存类型", "喪屍末日生存類型"],
    "새벽 3시, 실검 1위 「좀비 실화냐」. 세상이 뒤집혔다. 이 아수라장에서 너는 며칠 버틸 인간일까?": ["3 AM, #1 trending: \"Zombies, for real?\" The world has flipped. How long would you survive this chaos?", "3 AM, tendencia #1: «¿Zombis, en serio?». El mundo se volteó. ¿Cuánto sobrevivirías?", "Jam 3 pagi, trending #1: \"Zombi beneran?\" Dunia terbalik. Berapa lama kamu bertahan?", "深夜3時、トレンド1位「ゾンビってマジ？」世界がひっくり返った。この修羅場で君は何日もつ？", "ตี 3 เทรนด์อันดับ 1 «ซอมบี้ของจริง?» โลกพลิกคว่ำ คุณจะรอดได้กี่วัน?", "凌晨3点，热搜第一「丧尸是真的吗」。世界翻了。这场混乱里你能撑几天？", "凌晨3點，熱搜第一「喪屍是真的嗎」。世界翻了。這場混亂裡你能撐幾天？"],
    "좀비 생존 유형": ["Zombie Survival Type", "Tipo de supervivencia", "Tipe Bertahan Zombi", "ゾンビ生存タイプ", "ประเภทเอาตัวรอด", "丧尸生存类型", "喪屍生存類型"],
    "생존 확률": ["Survival rate", "Prob. de sobrevivir", "Peluang bertahan", "生存確率", "โอกาสรอด", "生存概率", "生存機率"],
    "필수템:": ["Must-have:", "Imprescindible:", "Barang wajib:", "必須アイテム:", "ไอเทมจำเป็น:", "必备:", "必備:"],
    "🎒 생존 필수템 —": ["🎒 Survival must-have —", "🎒 Imprescindible —", "🎒 Barang wajib —", "🎒 生存必須アイテム —", "🎒 ไอเทมเอาชีวิตรอด —", "🎒 生存必备 —", "🎒 生存必備 —"],

    // 유형
    "인간 내비게이션 리더형": ["Human-GPS Leader", "Líder GPS humano", "Pemimpin GPS Manusia", "人間ナビ・リーダー型", "ผู้นำ GPS มนุษย์", "人形导航领袖型", "人形導航領袖型"],
    "패닉? 그건 제 담당이 아닌데요": ["Panic? Not my department", "¿Pánico? No es mi departamento", "Panik? Bukan bagianku", "パニック？それは担当外です", "แพนิก? ไม่ใช่หน้าที่ฉัน", "恐慌？那不归我管", "恐慌？那不歸我管"],
    "세상이 뒤집힌 순간에도 혼자 침착하게 동선을 짜고 있는 타입. 다들 당신 뒤통수만 보고 따라 걷는데, 정작 본인 밥이랑 잠은 제일 뒤로 미루는 게 최대 리스크입니다.": ["Even as the world collapses, you're calmly mapping routes. Everyone follows the back of your head — but pushing your own meals and sleep to last place is your biggest risk.", "Mientras el mundo colapsa, tú trazas rutas con calma. Todos siguen tu nuca — pero postergar tu comida y sueño es tu mayor riesgo.", "Saat dunia runtuh, kamu tenang menyusun rute. Semua mengikutimu — tapi menunda makan dan tidurmu sendiri adalah risiko terbesarmu.", "世界がひっくり返った瞬間も一人冷静にルートを組むタイプ。みんな君の後頭部を見て歩くが、自分のご飯と睡眠を後回しにするのが最大のリスク。", "โลกพังแค่ไหนคุณก็ยังนั่งวางแผนเส้นทางอย่างใจเย็น ทุกคนเดินตามคุณ แต่ความเสี่ยงสูงสุดคือคุณผัดข้าวผัดนอนของตัวเองไว้ท้ายสุด", "世界翻了你还在冷静规划路线。大家都跟着你走——但把自己的饭和觉排到最后才是你最大的风险。", "世界翻了你還在冷靜規劃路線。大家都跟著你走——但把自己的飯和覺排到最後才是你最大的風險。"],
    "단톡 공지 쓰는 속도가 재난문자보다 빠름": ["Posts group notices faster than emergency alerts", "Publica avisos más rápido que las alertas oficiales", "Menulis pengumuman grup lebih cepat dari SMS darurat", "グルチャの告知が緊急速報より速い", "โพสต์ประกาศไวกว่า SMS เตือนภัย", "发群公告比灾难警报还快", "發群公告比災難警報還快"],
    "「일단 진정하고」가 시그니처 대사": ["\"Okay, everyone calm down\" is your signature line", "«A ver, calma» es tu frase estrella", "\"Tenang dulu semua\" adalah kalimat khasmu", "「まず落ち着いて」が決めゼリフ", "«ใจเย็นก่อนทุกคน» คือประโยคประจำตัว", "「先冷静一下」是你的招牌台词", "「先冷靜一下」是你的招牌台詞"],
    "본인 컨디션은 항상 담당자 부재중": ["Your own well-being? Manager currently unavailable", "¿Tu propio bienestar? Encargado ausente", "Kondisimu sendiri? Petugasnya selalu tidak di tempat", "自分のコンディション担当は常に不在", "สุขภาพตัวเอง? เจ้าหน้าที่ไม่อยู่เสมอ", "自己的状态？负责人常年不在岗", "自己的狀態？負責人常年不在崗"],
    "확성기 (없으면 목청)": ["Megaphone (or just your voice)", "Megáfono (o tu garganta)", "Megafon (kalau tak ada, pakai suara)", "拡声器（なければ地声）", "โทรโข่ง (ไม่มีก็ใช้เสียงตัวเอง)", "扩音器（没有就靠嗓门）", "擴音器（沒有就靠嗓門）"],
    "리더형": ["Leader", "Líder", "Pemimpin", "リーダー型", "สายผู้นำ", "领袖型", "領袖型"],

    "프라이팬 전투민족형": ["Frying-Pan Warrior", "Guerrero del sartén", "Pejuang Wajan", "フライパン戦闘民族型", "นักรบกระทะเหล็ก", "平底锅战斗民族型", "平底鍋戰鬥民族型"],
    "말보다 스윙이 빠름": ["Swings faster than words", "El golpe llega antes que la palabra", "Ayunan lebih cepat dari kata-kata", "言葉よりスイングが速い", "เหวี่ยงไวกว่าพูด", "挥锅比说话快", "揮鍋比說話快"],
    "위협 감지 즉시 몸이 먼저 나가는 타입. 무리의 방패를 자처하는 든든함이 무기지만, 가끔은 프라이팬보다 머리를 먼저 쓰는 연습이 필요합니다. 좀비보다 문틀에 부딪혀 다칠 확률이 더 높음.": ["Your body moves before your brain when danger appears. Being the group's shield is your strength — but sometimes try using your head before the pan. You're more likely to get hurt by a door frame than a zombie.", "Tu cuerpo reacciona antes que tu cerebro. Ser el escudo del grupo es tu fuerza — pero a veces usa la cabeza antes que el sartén. Es más probable que te lastime un marco de puerta que un zombi.", "Tubuhmu bergerak duluan saat ada ancaman. Jadi tameng kelompok itu kekuatanmu — tapi sesekali pakai kepala dulu sebelum wajan. Kamu lebih mungkin terluka kena kusen pintu daripada zombi.", "脅威を感知した瞬間、体が先に出るタイプ。群れの盾を買って出る頼もしさが武器だが、たまにはフライパンより頭を先に使う練習を。ゾンビよりドア枠にぶつかって怪我する確率のほうが高い。", "เจออันตรายปุ๊บร่างกายพุ่งก่อนสมอง การเป็นโล่ให้ทีมคือจุดแข็ง แต่บางทีลองใช้หัวก่อนใช้กระทะบ้าง โอกาสเจ็บเพราะชนขอบประตูสูงกว่าโดนซอมบี้", "察觉威胁身体比脑子先动。甘当团队盾牌是你的强项——但偶尔试试先动脑再动锅。你被门框撞伤的概率比被丧尸咬还高。", "察覺威脅身體比腦子先動。甘當團隊盾牌是你的強項——但偶爾試試先動腦再動鍋。你被門框撞傷的機率比被喪屍咬還高。"],
    "헬스장 3대 운동이 드디어 빛을 보는 순간": ["Your gym gains finally see the light", "Tus años de gimnasio por fin brillan", "Latihan gym-mu akhirnya terpakai", "ジムのBIG3がついに日の目を見る瞬間", "กล้ามที่สร้างในยิมได้ใช้งานจริงสักที", "健身房三大项终于派上用场", "健身房三大項終於派上用場"],
    "도망 루트보다 정면 루트를 먼저 검토": ["Considers the frontal route before the escape route", "Evalúa el ataque frontal antes que la huida", "Mempertimbangkan jalur frontal sebelum jalur kabur", "逃走ルートより正面ルートを先に検討", "คิดเส้นทางบุกก่อนเส้นทางหนี", "先考虑正面刚而不是逃跑路线", "先考慮正面剛而不是逃跑路線"],
    "전투 후 「별거 아니네」 (손 떨면서)": ["After the fight: \"That was nothing\" (hands shaking)", "Tras la pelea: «No fue nada» (manos temblando)", "Setelah bertarung: \"Gampang kok\" (tangan gemetar)", "戦闘後「大したことないな」（手は震えてる）", "หลังสู้เสร็จ: «จิ๊บ ๆ» (มือสั่นอยู่)", "打完之后「没什么嘛」（手在抖）", "打完之後「沒什麼嘛」（手在抖）"],
    "이모님 프라이팬 (28cm 이상)": ["Auntie's frying pan (28cm+)", "Sartén de la tía (28cm+)", "Wajan bibi (28cm+)", "おばちゃんのフライパン（28cm以上）", "กระทะป้า (28ซม.ขึ้นไป)", "阿姨的平底锅（28cm以上）", "阿姨的平底鍋（28cm以上）"],
    "전투형": ["Fighter", "Guerrero", "Petarung", "戦闘型", "สายบู๊", "战斗型", "戰鬥型"],

    "인간 편의점 살림꾼형": ["Human Convenience Store", "Tienda de conveniencia humana", "Minimarket Berjalan", "人間コンビニ・世話役型", "ร้านสะดวกซื้อเดินได้", "人形便利店管家型", "人形便利店管家型"],
    "말만 해, 가방에서 나오니까": ["Just say it — it's in my bag", "Solo pídelo — está en mi mochila", "Bilang saja — semuanya ada di tasku", "言ってみ、カバンから出てくるから", "บอกมาเถอะ เดี๋ยวหยิบจากกระเป๋าให้", "说吧，我包里都有", "說吧，我包裡都有"],
    "물·식량·보조배터리·상비약까지 야무지게 갖춘 진짜 생존 실세. 다들 당신 가방만 믿고 다니는데, 정작 본인 몫은 늘 제일 적게 챙기는 게 유일한 버그입니다. 아포칼립스 최고 연봉 직군.": ["Water, food, power banks, first aid — you're the real survival MVP. Everyone trusts your backpack, but your only bug is always keeping the smallest share for yourself. Highest-paid job of the apocalypse.", "Agua, comida, baterías, botiquín — eres el verdadero MVP. Todos confían en tu mochila, pero tu único bug es quedarte siempre con la menor parte. El puesto mejor pagado del apocalipsis.", "Air, makanan, power bank, obat — kamu MVP bertahan hidup sejati. Semua mengandalkan tasmu, tapi satu-satunya bug-mu: jatahmu sendiri selalu paling sedikit. Profesi bergaji tertinggi di kiamat.", "水・食料・モバイルバッテリー・常備薬まで抜かりなく揃えた真の生存実力者。みんな君のカバンだけを頼りにするが、自分の分はいつも一番少ないのが唯一のバグ。アポカリプス最高年俸職。", "น้ำ อาหาร พาวเวอร์แบงก์ ยาสามัญ ครบหมด คุณคือตัวจริงสายเอาตัวรอด ทุกคนพึ่งกระเป๋าคุณ แต่บั๊กเดียวคือส่วนของตัวเองน้อยสุดตลอด อาชีพเงินเดือนสูงสุดยุคล่มสลาย", "水·食物·充电宝·常备药一应俱全，真正的生存实力派。大家全靠你的背包，唯一的bug是自己那份永远留最少。末日最高薪职业。", "水·食物·行動電源·常備藥一應俱全，真正的生存實力派。大家全靠你的背包，唯一的bug是自己那份永遠留最少。末日最高薪職業。"],
    "재난 나기 전부터 이미 반쯤 준비돼 있었음": ["Half-prepared even before the disaster hit", "Ya estabas medio preparado antes del desastre", "Sudah setengah siap bahkan sebelum bencana", "災害が起きる前から半分準備できてた", "เตรียมพร้อมครึ่งหนึ่งตั้งแต่ก่อนภัยมา", "灾难来临前就已经准备了一半", "災難來臨前就已經準備了一半"],
    "「그거 나한테 있어」 발동 확률 99%": ["\"I've got that\" activation rate: 99%", "«Yo tengo eso» — probabilidad del 99%", "Peluang bilang \"Aku punya itu\": 99%", "「それ、持ってるよ」発動率99%", "อัตราการพูด «อันนั้นฉันมี»: 99%", "「那个我有」触发率99%", "「那個我有」觸發率99%"],
    "물물교환 시세를 혼자 다 꿰고 있음": ["Knows every barter exchange rate by heart", "Domina todas las tasas de trueque", "Hafal semua kurs barter di luar kepala", "物々交換のレートを一人で全部把握", "รู้เรตแลกเปลี่ยนของทุกอย่างคนเดียว", "以物易物的行情全在你脑子里", "以物易物的行情全在你腦子裡"],
    "27칸 수납 배낭": ["27-pocket backpack", "Mochila de 27 compartimentos", "Ransel 27 kantong", "27ポケット収納リュック", "เป้ 27 ช่อง", "27格收纳背包", "27格收納背包"],
    "살림꾼형": ["Provider", "Proveedor", "Penyedia", "世話役型", "สายเสบียง", "管家型", "管家型"],

    "자발적 무인도 은둔형": ["Voluntary Hermit", "Ermitaño voluntario", "Pertapa Sukarela", "自発的無人島・隠遁型", "ฤๅษีสมัครใจ", "自愿荒岛隐居型", "自願荒島隱居型"],
    "인류보다 와이파이가 그리움": ["Misses Wi-Fi more than humanity", "Extraña el Wi-Fi más que a la humanidad", "Lebih rindu Wi-Fi daripada umat manusia", "人類よりWi-Fiが恋しい", "คิดถึง Wi-Fi มากกว่ามนุษยชาติ", "比起人类更想念Wi-Fi", "比起人類更想念Wi-Fi"],
    "무리 생활보다 혼자가 백배 편한 타입. 아무도 못 찾는 안전가옥을 귀신같이 발굴하고 조용히 오래 살아남습니다. 다만 세상이 복구된 뒤에도 3주쯤 더 은둔하다가 뉴스 보고 나올 예정.": ["Being alone beats group life a hundred times over. You uncannily find safehouses no one else can and quietly outlast everyone. You'll probably stay hidden 3 more weeks after the world recovers, emerging only after seeing the news.", "Estar solo supera cien veces la vida en grupo. Encuentras refugios que nadie halla y sobrevives en silencio. Seguirás escondido 3 semanas más tras la recuperación, saliendo solo al ver las noticias.", "Sendirian seratus kali lebih nyaman daripada hidup berkelompok. Kamu jago menemukan rumah aman tersembunyi dan bertahan paling lama. Setelah dunia pulih pun kamu masih sembunyi 3 minggu, baru keluar setelah lihat berita.", "群れ生活より一人が百倍楽なタイプ。誰にも見つからない隠れ家を神業で発掘し、静かに長く生き残る。ただし世界が復旧した後も3週間ほど隠遁を続け、ニュースを見てから出てくる予定。", "อยู่คนเดียวสบายกว่าอยู่กลุ่มร้อยเท่า คุณหาบ้านปลอดภัยที่ไม่มีใครเจอได้อย่างเทพ และรอดแบบเงียบ ๆ ยาวนาน แต่หลังโลกฟื้นฟูก็จะเก็บตัวต่ออีก 3 สัปดาห์ ค่อยออกมาหลังดูข่าว", "独处比群居舒服一百倍。你总能神奇地找到没人发现的安全屋，安静地活到最后。世界恢复后你还会再隐居三周，看了新闻才出来。", "獨處比群居舒服一百倍。你總能神奇地找到沒人發現的安全屋，安靜地活到最後。世界恢復後你還會再隱居三週，看了新聞才出來。"],
    "집순이/집돌이 경력이 곧 생존 스펙": ["Your homebody career is now a survival credential", "Tu experiencia casera ahora es currículum de supervivencia", "Karier anak rumahan kini jadi keahlian bertahan", "インドア歴がそのまま生存スペック", "ประสบการณ์เก็บตัวคือสกิลเอาตัวรอด", "宅家资历就是生存履历", "宅家資歷就是生存履歷"],
    "기척 지우기 패시브 스킬 보유": ["Passive skill: presence erasure", "Habilidad pasiva: borrar tu presencia", "Skill pasif: menghapus kehadiran", "気配消しのパッシブスキル持ち", "สกิลติดตัว: ลบการมีตัวตน", "被动技能：抹除存在感", "被動技能:抹除存在感"],
    "가끔 사람 목소리가 그리워서 라디오 켬": ["Sometimes turns on the radio just to hear voices", "A veces enciende la radio solo por oír voces", "Kadang menyalakan radio hanya demi suara manusia", "たまに人の声が恋しくてラジオをつける", "บางทีเหงาเสียงคนเลยเปิดวิทยุ", "偶尔想念人声就打开收音机", "偶爾想念人聲就打開收音機"],
    "자물쇠 3종 세트": ["Triple lock set", "Set de 3 candados", "Set 3 gembok", "南京錠3種セット", "ชุดแม่กุญแจ 3 ชั้น", "三重锁具套装", "三重鎖具套裝"],
    "은둔형": ["Hermit", "Ermitaño", "Pertapa", "隠遁型", "สายเก็บตัว", "隐居型", "隱居型"],

    "생존 지상주의 계산형": ["Survival-First Calculator", "Calculador supervivencialista", "Kalkulator Prioritas Selamat", "生存至上・計算型", "สายคำนวณเอาชีวิตรอด", "生存至上计算型", "生存至上計算型"],
    "미안, 근데 나는 살아야겠어": ["Sorry, but I have to live", "Perdón, pero yo tengo que vivir", "Maaf, tapi aku harus hidup", "ごめん、でも僕は生きたいんだ", "ขอโทษนะ แต่ฉันต้องรอด", "抱歉，但我得活下去", "抱歉，但我得活下去"],
    "위기의 순간 손익 계산이 제일 빠른 타입. 생존율은 전 유형 1위지만, 사태가 끝난 뒤 동창회 참석률은 전 유형 꼴찌가 될 예정입니다. 당신과 같은 조가 된 사람들에게 미리 심심한 위로를 전합니다.": ["Fastest cost-benefit calculator in a crisis. Your survival rate ranks #1 of all types — but your post-apocalypse reunion attendance will rank dead last. Our sincere condolences to whoever ends up on your team.", "El más rápido calculando costo-beneficio en crisis. Tu tasa de supervivencia es la #1 — pero tu asistencia a reuniones post-apocalipsis será la última. Condolencias anticipadas a tu equipo.", "Paling cepat menghitung untung-rugi saat krisis. Tingkat bertahanmu peringkat 1 — tapi kehadiranmu di reuni pasca-kiamat bakal juru kunci. Turut berduka untuk siapa pun yang sekelompok denganmu.", "危機の瞬間、損得計算が一番速いタイプ。生存率は全タイプ1位だが、事態収束後の同窓会出席率は全タイプ最下位になる予定。君と同じ班になった人たちに、先にお悔やみを申し上げる。", "คำนวณได้เสียไวสุดในยามวิกฤต อัตรารอดอันดับ 1 ของทุกสาย แต่อัตราเข้าร่วมงานเลี้ยงรุ่นหลังวิกฤตจะรั้งท้ายสุด ขอแสดงความเสียใจล่วงหน้ากับคนที่ได้อยู่ทีมเดียวกับคุณ", "危机时刻算得最快的人。生存率全类型第一——但灾后同学会出席率将垫底。提前向和你一组的人致以慰问。", "危機時刻算得最快的人。生存率全類型第一——但災後同學會出席率將墊底。提前向和你一組的人致以慰問。"],
    "비상구 위치를 무의식적으로 먼저 확인": ["Instinctively checks exit locations first", "Localiza las salidas por instinto", "Refleks mengecek lokasi pintu darurat duluan", "非常口の位置を無意識に先に確認", "เช็กทางหนีไฟก่อนโดยไม่รู้ตัว", "下意识先确认安全出口位置", "下意識先確認安全出口位置"],
    "「우리」보다 「나」가 0.3초 빠름": ["\"Me\" comes 0.3s faster than \"us\"", "«Yo» llega 0,3s antes que «nosotros»", "\"Aku\" 0,3 detik lebih cepat dari \"kita\"", "「私たち」より「私」が0.3秒速い", "«ฉัน» มาไวกว่า «พวกเรา» 0.3 วินาที", "「我」比「我们」快0.3秒", "「我」比「我們」快0.3秒"],
    "살아남고 나서 사과문 초안 작성 중": ["Drafting the apology letter after surviving", "Redactando la disculpa tras sobrevivir", "Menyusun draf permintaan maaf setelah selamat", "生き残ってから謝罪文の下書き作成中", "รอดแล้วค่อยร่างจดหมายขอโทษ", "活下来之后正在起草道歉信", "活下來之後正在起草道歉信"],
    "혼자만 아는 지도": ["A map only you know", "Un mapa que solo tú conoces", "Peta yang hanya kamu tahu", "自分だけが知る地図", "แผนที่ที่มีแค่คุณที่รู้", "只有你知道的地图", "只有你知道的地圖"],
    "계산형": ["Calculator", "Calculador", "Kalkulator", "計算型", "สายคำนวณ", "计算型", "計算型"],

    "호기심 만렙 첫날사망형": ["Max-Curiosity Day-One Casualty", "Curioso caído el día uno", "Korban Hari Pertama Si Penasaran", "好奇心MAX・初日死亡型", "สายอยากรู้ ตายวันแรก", "好奇心满级首日阵亡型", "好奇心滿級首日陣亡型"],
    "그래도 궁금한 건 궁금한 거잖아": ["But curious is curious, right?", "Pero la curiosidad es la curiosidad, ¿no?", "Tapi penasaran ya penasaran, kan?", "でも気になるものは気になるじゃん", "แต่ก็อยากรู้อ่ะ ทำไงได้", "但好奇就是好奇嘛", "但好奇就是好奇嘛"],
    "사이렌이 울리면 숨는 게 아니라 창문부터 여는 타입. 「진짜 좀비인지 눈으로 봐야 믿지」라는 실증주의 정신이 이번 생에서만큼은 수명을 크게 단축시킵니다. 대신 당신이 남긴 영상은 인류의 귀중한 자료가 될 것입니다.": ["When sirens blare, you open the window instead of hiding. Your \"I'll believe zombies when I see them\" empiricism will drastically shorten this particular life. But the footage you leave behind will become humanity's precious archive.", "Cuando suenan las sirenas, abres la ventana en vez de esconderte. Tu espíritu de «lo creo cuando lo vea» acortará mucho esta vida. Pero tu grabación será un archivo valioso para la humanidad.", "Saat sirene berbunyi, kamu malah buka jendela. Semangat \"lihat dulu baru percaya\"-mu akan sangat memperpendek umurmu kali ini. Tapi rekamanmu akan jadi arsip berharga umat manusia.", "サイレンが鳴ったら隠れるのではなく、まず窓を開けるタイプ。「本物のゾンビか目で見なきゃ信じない」という実証主義精神が、今生に限っては寿命を大幅に縮める。代わりに君が残した映像は人類の貴重な資料になるだろう。", "ไซเรนดังแทนที่จะซ่อน คุณเปิดหน้าต่างก่อน จิตวิญญาณ «ต้องเห็นกับตาถึงเชื่อ» จะทำให้ชาตินี้สั้นลงมาก แต่คลิปที่คุณทิ้งไว้จะเป็นหลักฐานล้ำค่าของมนุษยชาติ", "警报一响你不躲反而先开窗。「不亲眼看到丧尸我不信」的实证精神将大幅缩短你这辈子的寿命。但你留下的视频将成为人类宝贵的资料。", "警報一響你不躲反而先開窗。「不親眼看到喪屍我不信」的實證精神將大幅縮短你這輩子的壽命。但你留下的影片將成為人類寶貴的資料。"],
    "재난 영상 항상 제일 앞에서 찍는 사람": ["Always filming disasters from the front row", "Siempre grabando el desastre en primera fila", "Selalu merekam bencana dari barisan terdepan", "災害映像をいつも最前列で撮る人", "ถ่ายคลิปภัยพิบัติแถวหน้าสุดตลอด", "灾难视频永远站最前排拍的人", "災難影片永遠站最前排拍的人"],
    "「에이 설마」가 마지막 유언 유력 후보": ["\"Nah, no way\" — leading candidate for your last words", "«Nah, imposible» — candidata a últimas palabras", "\"Ah, masa sih\" — kandidat kuat kata terakhirmu", "「いや、まさか」が最後の言葉の最有力候補", "«เฮ้ย ไม่หรอกมั้ง» เต็งหนึ่งคำพูดสุดท้าย", "「不会吧」是你遗言的最热门候选", "「不會吧」是你遺言的最熱門候選"],
    "전생에 고양이었다면 이미 9번 다 씀": ["If you were a cat before, all 9 lives are spent", "Si fuiste gato, ya gastaste las 9 vidas", "Kalau dulu kucing, 9 nyawamu sudah habis", "前世が猫なら9つの命はもう使い切った", "ถ้าชาติก่อนเป็นแมว 9 ชีวิตคงใช้หมดแล้ว", "如果你前世是猫，九条命早用完了", "如果你前世是貓，九條命早用完了"],
    "유서 겸 브이로그 카메라": ["A camera for vlogs (and your will)", "Cámara para vlogs (y testamento)", "Kamera vlog merangkap surat wasiat", "遺書兼Vlogカメラ", "กล้อง Vlog ควบพินัยกรรม", "遗书兼Vlog相机", "遺書兼Vlog相機"],
    "첫날사망형": ["Day-One Casualty", "Caído el día uno", "Korban Hari Pertama", "初日死亡型", "สายตายวันแรก", "首日阵亡型", "首日陣亡型"],

    // 케미 라벨
    "🤝 같은 조 하고 싶은": ["🤝 Dream teammate:", "🤝 Compañero soñado:", "🤝 Rekan tim impian:", "🤝 同じ班になりたい:", "🤝 อยากอยู่ทีมเดียวกับ:", "🤝 最想同队的:", "🤝 最想同隊的:"],
    "💥 같은 조 되면 대환장": ["💥 Total chaos teammate:", "💥 Caos total con:", "💥 Kekacauan total bersama:", "💥 同じ班だと大混乱:", "💥 อยู่ทีมเดียวกันคือวุ่นวาย:", "💥 同队就大乱的:", "💥 同隊就大亂的:"],

    // 질문 & 선택지
    "새벽 3시, 커뮤에 「우리 동네 좀비 실화냐」 글이 실검 1위. 창밖에서 진짜 「우어어…」 소리가 들린다.": ["3 AM. \"Zombies in my neighborhood, for real?\" tops the trends. Then you hear an actual \"Uurrgh…\" outside your window.", "3 AM. «¿Zombis en mi barrio?» es tendencia #1. Y oyes un «Uurrgh…» real afuera.", "Jam 3 pagi. \"Zombi di komplek, beneran?\" trending #1. Lalu terdengar \"Uurrgh…\" sungguhan di luar jendela.", "深夜3時、「うちの町にゾンビってマジ？」がトレンド1位。窓の外から本物の「ウァァ…」が聞こえる。", "ตี 3 กระทู้ «ซอมบี้แถวบ้านของจริง?» ขึ้นเทรนด์อันดับ 1 แล้วก็ได้ยินเสียง «อือออ…» จริง ๆ นอกหน้าต่าง", "凌晨3点，「我们小区有丧尸是真的吗」冲上热搜第一。窗外传来真实的「呃啊…」声。", "凌晨3點，「我們社區有喪屍是真的嗎」衝上熱搜第一。窗外傳來真實的「呃啊…」聲。"],
    "창문 열고 직접 확인 + 세로 영상 촬영. 「와 미쳤다 이거 실화임?」": ["Open the window to check + film vertical video. \"Whoa, insane, is this real?\"", "Abrir la ventana y grabar en vertical. «¡Qué locura! ¿Es real?»", "Buka jendela + rekam video vertikal. \"Gila, ini beneran?\"", "窓を開けて直接確認＋縦動画撮影。「うわヤバ、これマジ？」", "เปิดหน้าต่างเช็กเอง + ถ่ายคลิปแนวตั้ง «โอ้โห ของจริงปะเนี่ย?»", "开窗亲自确认+拍竖屏视频。「哇疯了这是真的吗？」", "開窗親自確認+拍直屏影片。「哇瘋了這是真的嗎？」"],
    "가족톡·친구톡에 즉시 행동지침 전파. 「1. 문 잠가 2. 불 꺼 3. 톡 확인」": ["Blast action protocols to family & friend chats: \"1. Lock doors 2. Lights off 3. Check chat\"", "Enviar protocolo a los chats: «1. Cierra 2. Apaga luces 3. Revisa el chat»", "Sebar protokol ke grup keluarga & teman: \"1. Kunci pintu 2. Matikan lampu 3. Cek chat\"", "家族・友達グルチャに即行動指針を配信。「1.ドアを施錠 2.消灯 3.トーク確認」", "ส่งคู่มือปฏิบัติเข้ากลุ่มครอบครัว-เพื่อนทันที «1.ล็อกประตู 2.ปิดไฟ 3.เช็กแชท»", "立刻向家人群·朋友群发布行动指南：「1.锁门 2.关灯 3.看群」", "立刻向家人群·朋友群發布行動指南:「1.鎖門 2.關燈 3.看群」"],
    "프라이팬 들고 현관 앞 1인 방어선 구축": ["Grab a frying pan and form a one-person defense line at the door", "Con el sartén, montar una línea de defensa unipersonal en la puerta", "Angkat wajan, bangun garis pertahanan satu orang di depan pintu", "フライパンを持って玄関前に1人防衛線を構築", "คว้ากระทะตั้งแนวป้องกันคนเดียวหน้าประตู", "拎起平底锅在玄关筑起一人防线", "拎起平底鍋在玄關築起一人防線"],
    "조용히 소등 + 커튼 클로즈. 오늘부로 이 집은 빈집이다": ["Quietly kill the lights + close curtains. As of today, this house is empty.", "Apagar luces y cerrar cortinas. Desde hoy, esta casa está vacía.", "Diam-diam matikan lampu + tutup gorden. Mulai hari ini rumah ini kosong.", "静かに消灯＋カーテンクローズ。本日をもってこの家は空き家です", "ปิดไฟเงียบ ๆ + รูดม่าน ตั้งแต่วันนี้บ้านนี้คือบ้านร้าง", "悄悄关灯+拉上窗帘。从今天起这是空房", "悄悄關燈+拉上窗簾。從今天起這是空房"],

    "단톡 3개가 동시에 폭발 중 — 가족톡 47, 친구톡 213, 과톡/회사톡 89. 뭐부터 하지?": ["Three group chats exploding at once — family 47, friends 213, class/work 89. What first?", "Tres chats explotando — familia 47, amigos 213, trabajo 89. ¿Qué primero?", "Tiga grup meledak bersamaan — keluarga 47, teman 213, kampus/kantor 89. Mulai dari mana?", "グルチャ3つが同時爆発中 — 家族47、友達213、ゼミ/会社89。どれから？", "แชท 3 กลุ่มระเบิดพร้อมกัน — ครอบครัว 47 เพื่อน 213 คณะ/บริษัท 89 เอาไงก่อน?", "三个群同时爆炸——家人群47条，朋友群213条，班级/公司群89条。先看哪个？", "三個群同時爆炸——家人群47條，朋友群213條，班級/公司群89條。先看哪個？"],
    "과톡에 집결지·시간 공지 박고 고정. 「이견 있으면 3분 안에」": ["Pin rally point & time in the class chat: \"Objections within 3 minutes\"", "Fijar punto y hora en el chat: «Objeciones en 3 minutos»", "Sematkan titik kumpul & waktu: \"Keberatan dalam 3 menit\"", "ゼミトークに集合場所・時間を告知しピン留め。「異議は3分以内に」", "ปักหมุดจุดรวมพลและเวลา «มีข้อโต้แย้งภายใน 3 นาที»", "在群里置顶集合点·时间：「有异议3分钟内提」", "在群裡置頂集合點·時間:「有異議3分鐘內提」"],
    "각 톡방에 준비물 리스트 전송 — 물 2L, 보조배터리, 상비약…": ["Send supply lists to every chat — 2L water, power bank, first aid…", "Enviar lista de suministros — 2L de agua, batería, botiquín…", "Kirim daftar perbekalan ke tiap grup — air 2L, power bank, obat…", "各トークに準備物リストを送信 — 水2L、モバイルバッテリー、常備薬…", "ส่งลิสต์ของจำเป็นทุกกลุ่ม — น้ำ 2 ลิตร พาวเวอร์แบงก์ ยา…", "给每个群发物资清单——水2L、充电宝、常备药…", "給每個群發物資清單——水2L、行動電源、常備藥…"],
    "전부 읽씹하고 조용히 혼자 짐 싸는 중. 단체행동은 느리다": ["Ignore them all and quietly pack alone. Group action is slow.", "Ignorar todo y empacar solo. Los grupos son lentos.", "Abaikan semua, diam-diam berkemas sendiri. Aksi kelompok itu lambat.", "全部既読スルーで静かに一人荷造り中。団体行動は遅い", "อ่านแล้วเมินหมด เก็บของเงียบ ๆ คนเดียว ทีมเวิร์กมันช้า", "全部已读不回，默默自己收拾行李。集体行动太慢", "全部已讀不回，默默自己收拾行李。集體行動太慢"],
    "친구톡에 「ㄹㅇ?ㅋㅋ」 보내고 구경하러 나갈 채비": ["Send \"fr? lol\" to friends and gear up to go watch", "Mandar «¿en serio? jaja» y salir a mirar", "Kirim \"serius? wkwk\" lalu siap-siap keluar nonton", "友達トークに「マ？ｗ」と送って見物に出る準備", "ส่ง «จริงดิ 555» ในกลุ่มเพื่อนแล้วเตรียมออกไปดู", "在朋友群发「真的假的哈哈」然后准备出门围观", "在朋友群發「真的假的哈哈」然後準備出門圍觀"],

    "대피소에서 마지막 남은 보조배터리 1개. 옆 생존자도 폰 배터리 3%다.": ["One last power bank at the shelter. The survivor next to you is also at 3% battery.", "Última batería del refugio. El de al lado también tiene 3%.", "Power bank terakhir di pengungsian. Penyintas sebelah juga tinggal 3%.", "避難所に残った最後のモバイルバッテリー1個。隣の生存者もバッテリー3%。", "พาวเวอร์แบงก์ก้อนสุดท้ายในศูนย์อพยพ คนข้าง ๆ แบตก็เหลือ 3%", "避难所里最后一个充电宝。旁边的幸存者手机也只剩3%电。", "避難所裡最後一個行動電源。旁邊的倖存者手機也只剩3%電。"],
    "「팔씨름으로 정하죠」 (소매 걷으며 이미 이긴 표정)": ["\"Arm wrestling decides it\" (rolling up sleeves with a winner's face)", "«Lo decide un pulso» (arremangándose, cara de ganador)", "\"Panco saja\" (gulung lengan, wajah sudah menang)", "「腕相撲で決めましょう」（袖をまくって既に勝った顔）", "«งัดข้อกันเถอะ» (ถกแขนเสื้อ หน้าเหมือนชนะแล้ว)", "「掰手腕决定吧」（挽袖子，一脸已经赢了的表情）", "「掰手腕決定吧」（挽袖子，一臉已經贏了的表情）"],
    "상대가 한눈판 사이에… 어? 내 주머니에 있네?": ["While they're distracted… huh? It's in my pocket?", "Mientras se distrae… ¿eh? ¿Está en mi bolsillo?", "Saat dia lengah… lho? Kok ada di sakuku?", "相手がよそ見した隙に…あれ？僕のポケットに？", "จังหวะเขาเผลอ… เอ๊ะ? อยู่ในกระเป๋าฉันได้ไง?", "趁对方走神…咦？怎么在我兜里？", "趁對方走神…咦？怎麼在我兜裡？"],
    "양보한다. 그리고 가방에서 태양광 충전기를 꺼낸다": ["Yield it — then pull a solar charger from your bag", "Cederlo — y sacar tu cargador solar de la mochila", "Mengalah — lalu keluarkan charger tenaga surya dari tas", "譲る。そしてカバンからソーラー充電器を取り出す", "ยอมให้ไป แล้วหยิบแผงโซลาร์ชาร์จจากกระเป๋า", "让给他——然后从包里掏出太阳能充电器", "讓給他——然後從包裡掏出太陽能充電器"],
    "「전 괜찮아요」 — 어차피 연락 올 사람 없음": ["\"I'm fine\" — nobody's texting you anyway", "«Estoy bien» — total, nadie te escribe", "\"Aku tidak apa-apa\" — toh tak ada yang menghubungi", "「僕は大丈夫です」— どうせ連絡くる人いない", "«ฉันไม่เป็นไร» — ยังไงก็ไม่มีใครทักมาอยู่แล้ว", "「我不用」——反正也没人联系我", "「我不用」——反正也沒人聯繫我"],

    "무법지대 된 편의점, 사실상 합법 약탈 타임. 너의 장바구니는?": ["The convenience store is lawless now — basically legal looting time. What's in your basket?", "La tienda sin ley — saqueo legal. ¿Qué llevas?", "Minimarket tanpa hukum — waktunya jarah legal. Isi keranjangmu?", "無法地帯と化したコンビニ、実質合法の略奪タイム。君のカゴの中身は？", "ร้านสะดวกซื้อไร้กฎหมาย ปล้นแบบถูกกฎหมายได้แล้ว ตะกร้าคุณมีอะไร?", "便利店成了无法地带，堪称合法打劫时间。你的购物篮里装什么？", "便利店成了無法地帶，堪稱合法打劫時間。你的購物籃裡裝什麼？"],
    "물·통조림·건전지 — 동선 최적화로 3분 컷 스윕": ["Water, cans, batteries — optimized route, 3-minute sweep", "Agua, latas, pilas — ruta optimizada, barrido en 3 min", "Air, kaleng, baterai — rute optimal, sapu bersih 3 menit", "水・缶詰・乾電池 — 動線最適化で3分スイープ", "น้ำ อาหารกระป๋อง ถ่านไฟฉาย — จัดเส้นทางกวาดเสร็จใน 3 นาที", "水·罐头·电池——路线最优化3分钟扫荡", "水·罐頭·電池——路線最優化3分鐘掃蕩"],
    "과자 코너에서 신상 발견. 「어? 이거 나온 거 몰랐는데」 시식 중": ["Found a new snack in the aisle. \"Oh? Didn't know this dropped\" — taste-testing", "Nuevo snack en el pasillo. «¿Y esto?» — degustando", "Nemu snack baru. \"Lho? Baru tahu ini rilis\" — icip-icip", "お菓子コーナーで新商品発見。「え？これ出てたの知らなかった」と試食中", "เจอขนมออกใหม่ «เอ๊ะ อันนี้ออกแล้วเหรอ» ชิมอยู่", "在零食区发现新品。「咦？不知道出了这个」试吃中", "在零食區發現新品。「咦？不知道出了這個」試吃中"],
    "우산·야구방망이·프라이팬 — 무기 코너(원래는 생활용품 코너)만 털음": ["Umbrellas, bats, frying pans — raiding only the weapons aisle (formerly housewares)", "Paraguas, bates, sartenes — solo el pasillo de armas (antes hogar)", "Payung, tongkat bisbol, wajan — hanya jarah rak senjata (dulunya alat rumah)", "傘・バット・フライパン — 武器コーナー（元・生活用品コーナー）だけ略奪", "ร่ม ไม้เบสบอล กระทะ — กวาดเฉพาะโซนอาวุธ (เดิมคือของใช้ในบ้าน)", "雨伞·球棒·平底锅——只扫武器区（原日用品区）", "雨傘·球棒·平底鍋——只掃武器區（原日用品區）"],
    "직접 안 담음. 남들이 담은 카트에서 필요한 것만 회수 예정": ["Not shopping myself — planning to \"recover\" essentials from others' carts", "No recojo nada — «recuperaré» lo necesario de otros carritos", "Tidak ambil sendiri — nanti \"ambil kembali\" dari troli orang", "自分では取らない。他人のカートから必要な物だけ回収予定", "ไม่หยิบเอง ว่าจะ «เก็บเกี่ยว» จากรถเข็นคนอื่นทีหลัง", "自己不拿。打算从别人购物车里回收所需", "自己不拿。打算從別人購物車裡回收所需"],

    "일행 중 한 명의 팔에 수상한 자국. 본인은 「모기 물린 거야!」라고 주장 중.": ["A suspicious mark on a teammate's arm. They insist: \"It's a mosquito bite!\"", "Marca sospechosa en el brazo de uno. Insiste: «¡Es un mosquito!»", "Bekas mencurigakan di lengan teman. Dia ngotot: \"Digigit nyamuk!\"", "仲間の一人の腕に怪しい痕。本人は「蚊に刺されただけ！」と主張中。", "แขนเพื่อนร่วมทีมมีรอยน่าสงสัย เจ้าตัวยืนยัน «ยุงกัด!»", "同伴手臂上有可疑痕迹。本人坚称「是蚊子咬的！」", "同伴手臂上有可疑痕跡。本人堅稱「是蚊子咬的！」"],
    "「확인만 하자. 규칙대로.」 침착하게 검사 절차 진행": ["\"Let's just check. By the rules.\" Calmly run the inspection", "«Solo revisemos. Según las reglas.» Inspección con calma", "\"Kita cek saja. Sesuai aturan.\" Jalankan pemeriksaan dengan tenang", "「確認だけしよう。ルール通りに。」冷静に検査手順を進行", "«ขอเช็กหน่อย ตามกติกา» ตรวจอย่างใจเย็น", "「按规矩检查一下。」冷静执行检查流程", "「按規矩檢查一下。」冷靜執行檢查流程"],
    "구급상자 들고 접근. 「일단 소독부터 하자, 응?」": ["Approach with the first aid kit. \"Let's disinfect first, okay?\"", "Acercarse con el botiquín. «Primero desinfectemos, ¿sí?»", "Mendekat bawa kotak P3K. \"Disinfeksi dulu ya?\"", "救急箱を持って接近。「まず消毒しよう、ね？」", "ถือกล่องปฐมพยาบาลเข้าไป «ล้างแผลก่อนนะ»", "拎着急救箱靠近。「先消毒一下，好吗？」", "拎著急救箱靠近。「先消毒一下，好嗎？」"],
    "그 사람 뒤쪽 자리로 조용히 이동 + 프라이팬 스탠바이": ["Quietly reposition behind them + frying pan on standby", "Moverse detrás en silencio + sartén en espera", "Diam-diam pindah ke belakangnya + wajan siaga", "その人の後ろの席へ静かに移動＋フライパンスタンバイ", "ย้ายไปนั่งข้างหลังเขาเงียบ ๆ + กระทะสแตนด์บาย", "悄悄挪到他身后+平底锅待命", "悄悄挪到他身後+平底鍋待命"],
    "그날 밤 짐 싸서 조용히 단독 이탈. 쪽지도 안 남김": ["Pack up that night and slip away alone. No note left.", "Esa noche, empacar y desaparecer solo. Sin nota.", "Malam itu berkemas dan pergi sendirian. Tanpa pesan.", "その夜、荷物をまとめて静かに単独離脱。メモも残さない", "คืนนั้นเก็บของแอบชิ่งคนเดียว โน้ตก็ไม่ทิ้งไว้", "当晚收拾行李悄悄单独撤离。连字条都不留", "當晚收拾行李悄悄單獨撤離。連字條都不留"],

    "인플루언서가 옥상에서 「좀비 챌린지」를 찍고 있다. 좀비들이 계단으로 올라가는 중.": ["An influencer is filming a \"zombie challenge\" on a rooftop. Zombies are climbing the stairs.", "Un influencer graba el «reto zombi» en la azotea. Los zombis suben.", "Influencer merekam \"tantangan zombi\" di atap. Zombi sedang naik tangga.", "インフルエンサーが屋上で「ゾンビチャレンジ」を撮影中。ゾンビが階段を上がっている。", "อินฟลูฯ ถ่าย «ชาเลนจ์ซอมบี้» บนดาดฟ้า ซอมบี้กำลังขึ้นบันได", "网红在天台拍「丧尸挑战」。丧尸正在爬楼梯。", "網紅在天台拍「喪屍挑戰」。喪屍正在爬樓梯。"],
    "「저거 찍히면 대박이다」 나도 옆 건물 옥상으로 이동": ["\"That'll be viral gold\" — heading to the next rooftop myself", "«Eso será viral» — voy a la azotea de al lado", "\"Itu bakal viral\" — aku pindah ke atap sebelah", "「あれ撮れたらバズる」自分も隣のビルの屋上へ移動", "«ถ่ายติดนี่ปังแน่» ขอย้ายไปดาดฟ้าตึกข้าง ๆ", "「拍到那个就爆了」我也转移到隔壁楼顶", "「拍到那個就爆了」我也轉移到隔壁樓頂"],
    "확성기 들고 「그 건물 즉시 대피하세요!」 방송": ["Grab the megaphone: \"Evacuate that building immediately!\"", "Con megáfono: «¡Evacuen ese edificio ya!»", "Angkat megafon: \"Segera evakuasi gedung itu!\"", "拡声器で「その建物から直ちに避難してください！」と放送", "คว้าโทรโข่ง «อพยพออกจากตึกนั้นเดี๋ยวนี้!»", "拿起扩音器广播「那栋楼立刻撤离！」", "拿起擴音器廣播「那棟樓立刻撤離！」"],
    "저 사람 장비… 삼각대랑 짐벌 좋은 거 쓰네. 이따 챙겨야지": ["That gear… nice tripod and gimbal. I'll collect those later.", "Ese equipo… buen trípode y gimbal. Luego los recojo.", "Peralatannya… tripod dan gimbal bagus. Nanti kuambil.", "あの人の機材…三脚とジンバル、いいの使ってるな。後で頂こう", "อุปกรณ์เขา… ขาตั้งกับกิมบอลดีนะ ไว้ค่อยไปเก็บ", "那人的装备…三脚架和云台不错。待会儿去收", "那人的裝備…三腳架和雲台不錯。待會兒去收"],
    "관심 없음. 그 시간에 은신처 2중 잠금장치 보강": ["Not interested. Using that time to add a second lock to the hideout.", "Sin interés. Mejor refuerzo el doble candado del refugio.", "Tidak tertarik. Waktunya kupakai memperkuat kunci ganda persembunyian.", "興味なし。その時間で隠れ家の二重ロックを補強", "ไม่สน เอาเวลาไปเสริมล็อก 2 ชั้นให้ที่ซ่อนดีกว่า", "没兴趣。用这时间给藏身处加固双重锁", "沒興趣。用這時間給藏身處加固雙重鎖"],

    "생존자 캠프 도착. 돌아가며 자기소개 겸 역할 지원 시간이다.": ["Arrived at the survivor camp. Time for introductions and role sign-ups.", "Llegas al campamento. Presentaciones y asignación de roles.", "Tiba di kamp penyintas. Waktunya perkenalan dan pembagian peran.", "生存者キャンプに到着。順番に自己紹介兼役割志願タイム。", "ถึงแคมป์ผู้รอดชีวิต ได้เวลาแนะนำตัวและสมัครหน้าที่", "抵达幸存者营地。轮流自我介绍兼报名分工。", "抵達倖存者營地。輪流自我介紹兼報名分工。"],
    "「동선 짜고 인원 관리하겠습니다」 — 어느새 화이트보드 앞에 서 있음": ["\"I'll handle routes and personnel\" — somehow already at the whiteboard", "«Yo organizo rutas y personal» — ya estás frente a la pizarra", "\"Aku atur rute dan personel\" — tahu-tahu sudah di depan papan tulis", "「動線と人員管理をやります」— 気づけばホワイトボードの前に立っている", "«ผมจัดเส้นทางกับกำลังคนเอง» — รู้ตัวอีกทีก็ยืนหน้าไวท์บอร์ดแล้ว", "「我来规划路线和管理人员」——不知不觉已站在白板前", "「我來規劃路線和管理人員」——不知不覺已站在白板前"],
    "「야간 경비 서겠습니다」 (프라이팬 들어 보이며)": ["\"I'll take night watch\" (raising the frying pan)", "«Haré la guardia nocturna» (alzando el sartén)", "\"Aku jaga malam\" (mengangkat wajan)", "「夜間警備をやります」（フライパンを掲げながら）", "«ผมเฝ้ายามกลางคืนเอง» (ชูกระทะ)", "「我来守夜」（举起平底锅）", "「我來守夜」（舉起平底鍋）"],
    "「물자 관리요. 참고로 지금 재고표 이미 만들었습니다」": ["\"Supplies. FYI, the inventory sheet is already done.\"", "«Suministros. El inventario ya está hecho, por cierto.»", "\"Logistik. FYI, daftar stoknya sudah jadi.\"", "「物資管理を。ちなみに在庫表はもう作ってあります」", "«ดูแลเสบียงครับ แล้วก็…ตารางสต๊อกทำเสร็จแล้วนะ»", "「物资管理。顺便说，库存表我已经做好了」", "「物資管理。順便說，庫存表我已經做好了」"],
    "「정찰 담당 하겠습니다」 (사실 그냥 구경 다니고 싶음)": ["\"I'll be the scout\" (really just wants to sightsee)", "«Seré explorador» (en verdad solo quiere pasear)", "\"Aku jadi pengintai\" (sebenarnya cuma mau jalan-jalan)", "「偵察担当をやります」（実はただ見物して回りたい）", "«ผมขอเป็นหน่วยลาดตระเวน» (จริง ๆ แค่อยากไปเดินดู)", "「我来负责侦察」（其实只是想到处逛）", "「我來負責偵察」（其實只是想到處逛）"],

    "구조 헬기 등장! 남은 좌석은 1개, 우리 일행은 4명.": ["Rescue chopper! One seat left — our group has four.", "¡Helicóptero! Un asiento — somos cuatro.", "Heli penyelamat! Kursi tersisa satu — kelompok kami berempat.", "救助ヘリ登場！残り座席は1つ、僕らは4人。", "เฮลิคอปเตอร์กู้ภัยมา! เหลือที่นั่งเดียว แต่พวกเรามี 4 คน", "救援直升机来了！只剩1个座位，我们一行4人。", "救援直升機來了！只剩1個座位，我們一行4人。"],
    "「미안!」 …소리가 들릴 땐 이미 탑승 완료": ["\"Sorry!\" …by the time they hear it, you're already aboard", "«¡Perdón!» …cuando lo oyen, ya estás a bordo", "\"Maaf!\" …saat terdengar, kamu sudah naik", "「ごめん！」…声が聞こえた時にはすでに搭乗完了", "«โทษที!» …เสียงดังถึงหู ตอนนั้นก็ขึ้นเครื่องไปแล้ว", "「抱歉！」…听到时你已登机完毕", "「抱歉！」…聽到時你已登機完畢"],
    "제일 약한 사람 태워 보내고 손 흔들어줌": ["Put the weakest aboard and wave them off", "Subir al más débil y despedirlo con la mano", "Naikkan yang paling lemah lalu lambaikan tangan", "一番弱い人を乗せて見送り、手を振ってあげる", "ส่งคนที่อ่อนแอสุดขึ้นไปแล้วโบกมือให้", "让最虚弱的人上去，挥手送别", "讓最虛弱的人上去，揮手送別"],
    "「헬기? 난 저거 안 믿어.」 걸어서 살아남는 길 선택": ["\"A chopper? I don't trust that thing.\" Choosing to survive on foot", "«¿Helicóptero? No me fío.» Sobrevivir a pie", "\"Heli? Aku tak percaya itu.\" Pilih bertahan jalan kaki", "「ヘリ？あれは信用しない。」歩いて生き残る道を選択", "«เฮลิคอปเตอร์? ไม่เชื่อหรอก» เลือกเดินเอาตัวรอดเอง", "「直升机？我不信那玩意。」选择徒步求生", "「直升機？我不信那玩意。」選擇徒步求生"],
    "타는 사람 주머니에 비상식량 쑤셔 넣어 보냄": ["Stuff emergency rations into the passenger's pockets before they go", "Meterle raciones de emergencia en los bolsillos al que sube", "Menjejalkan ransum darurat ke saku orang yang naik", "乗る人のポケットに非常食を詰め込んで見送る", "ยัดเสบียงฉุกเฉินใส่กระเป๋าคนที่ได้ขึ้นไป", "往上机的人兜里塞满应急口粮", "往上機的人兜裡塞滿應急口糧"],

    "폐허가 된 거리에서 좀비가 된 절친(혹은 전 애인)과 눈이 마주쳤다.": ["In the ruined streets, you lock eyes with your zombified best friend (or ex).", "En las ruinas, cruzas miradas con tu mejor amigo (o ex) zombi.", "Di jalanan hancur, kamu bertatapan dengan sahabat (atau mantan) yang jadi zombi.", "廃墟と化した街で、ゾンビになった親友（もしくは元恋人）と目が合った。", "บนถนนร้าง คุณสบตากับเพื่อนสนิท (หรือแฟนเก่า) ที่กลายเป็นซอมบี้", "在废墟街头，你和变成丧尸的挚友（或前任）对上了眼。", "在廢墟街頭，你和變成喪屍的摯友（或前任）對上了眼。"],
    "「야… 나 기억나?」 한 발짝 다가가며 말 걸어봄": ["\"Hey… remember me?\" Taking a step closer to talk", "«Oye… ¿me recuerdas?» Un paso más cerca", "\"Hei… ingat aku?\" Melangkah mendekat sambil bicara", "「なあ…俺のこと覚えてる？」一歩近づいて話しかけてみる", "«นี่… จำฉันได้ไหม?» ก้าวเข้าไปลองคุย", "「喂…还记得我吗？」上前一步搭话", "「喂…還記得我嗎？」上前一步搭話"],
    "눈 질끈 감고 스윙. 「미안… 이게 내 방식의 작별인사야」": ["Eyes shut tight, full swing. \"Sorry… this is my way of saying goodbye.\"", "Ojos cerrados, swing total. «Perdón… así me despido yo.»", "Pejamkan mata, ayun penuh. \"Maaf… ini caraku berpamitan.\"", "目をぎゅっとつぶってフルスイング。「ごめん…これが僕なりの別れの挨拶だ」", "หลับตาปี๋แล้วเหวี่ยงสุดแรง «ขอโทษ… นี่คือวิธีบอกลาแบบของฉัน»", "紧闭双眼挥出一击。「对不起…这是我的告别方式」", "緊閉雙眼揮出一擊。「對不起…這是我的告別方式」"],
    "눈 마주치기 전에 이미 옆 골목으로 증발한 상태": ["Already evaporated into a side alley before eye contact", "Ya evaporado en un callejón antes del contacto visual", "Sudah menguap ke gang sebelah sebelum sempat bertatapan", "目が合う前にすでに横道へ蒸発済み", "ยังไม่ทันสบตาก็ระเหยเข้าตรอกข้าง ๆ ไปแล้ว", "还没对上眼就已经蒸发进小巷", "還沒對上眼就已經蒸發進小巷"],
    "천천히 뒷걸음질하며 다른 좀비들 쪽으로 유인… 미안": ["Slowly backing up, luring them toward the other zombies… sorry", "Retrocediendo despacio, guiándolo hacia otros zombis… perdón", "Mundur pelan sambil memancingnya ke arah zombi lain… maaf", "ゆっくり後ずさりながら他のゾンビの方へ誘導…ごめん", "ค่อย ๆ ถอยหลังแล้วล่อไปทางซอมบี้ตัวอื่น… ขอโทษนะ", "慢慢后退把它引向其他丧尸…抱歉", "慢慢後退把它引向其他喪屍…抱歉"],

    "6개월 뒤, 생존자 다큐멘터리에 내가 나왔다. 화면 아래 소개 자막은?": ["Six months later, you appear in a survivor documentary. The caption under your face reads?", "Seis meses después, apareces en un documental. ¿Tu subtítulo en pantalla?", "Enam bulan kemudian kamu muncul di dokumenter penyintas. Keterangan di layar?", "6ヶ月後、生存者ドキュメンタリーに自分が出演。画面下の紹介テロップは？", "6 เดือนต่อมา คุณออกสารคดีผู้รอดชีวิต ซับใต้ภาพเขียนว่า?", "六个月后，你出现在幸存者纪录片里。画面下方的介绍字幕是？", "六個月後，你出現在倖存者紀錄片裡。畫面下方的介紹字幕是？"],
    "「프라이팬의 전설 — 좀비 격퇴 137회」": ["\"The Frying Pan Legend — 137 zombies repelled\"", "«La leyenda del sartén — 137 zombis repelidos»", "\"Legenda Wajan — 137 zombi ditumbangkan\"", "「フライパンの伝説 — ゾンビ撃退137回」", "«ตำนานกระทะเหล็ก — ปราบซอมบี้ 137 ครั้ง»", "「平底锅传奇——击退丧尸137次」", "「平底鍋傳奇——擊退喪屍137次」"],
    "「목격담만 존재하는 유령 생존자」": ["\"The ghost survivor who exists only in sightings\"", "«El superviviente fantasma que solo existe en rumores»", "\"Penyintas hantu yang hanya ada dalam cerita saksi\"", "「目撃談だけが存在する幽霊生存者」", "«ผู้รอดชีวิตเงา ที่มีแต่คำบอกเล่า»", "「只存在于目击传闻中的幽灵幸存者」", "「只存在於目擊傳聞中的幽靈倖存者」"],
    "「1화에서 하차 (시청자 여러분이 많이 우셨습니다)」": ["\"Left the show in episode 1 (viewers cried a lot)\"", "«Salió en el episodio 1 (los espectadores lloraron mucho)»", "\"Keluar di episode 1 (penonton banyak yang menangis)\"", "「第1話で降板（視聴者の皆さんが大泣きしました）」", "«ออกจากรายการตั้งแต่ตอนแรก (ผู้ชมร้องไห้หนักมาก)»", "「第1集下车（观众们哭得很惨）」", "「第1集下車（觀眾們哭得很慘）」"],
    "「전국 생존 캠프를 먹여 살린 물류왕」": ["\"The logistics king who fed every survivor camp in the country\"", "«El rey de la logística que alimentó todos los campamentos»", "\"Raja logistik yang menghidupi semua kamp penyintas\"", "「全国の生存キャンプを食わせた物流王」", "«ราชาโลจิสติกส์ผู้เลี้ยงดูแคมป์ทั่วประเทศ»", "「养活全国幸存者营地的物流之王」", "「養活全國倖存者營地的物流之王」"]
  });
})();
